# Global variables
monitoring_base_dir: /opt/monitoring
docker_compose_version: "3.8"

# Docker configuration
docker_network_name: monitoring

# Service ports
ports:
  prometheus: 9090
  grafana: 3000
  alertmanager: 9093
  node_exporter: 9100
  mongodb: 27017
  influxdb: 8086
  mosquitto: 1883
  nginx: 80

# Prometheus configuration
prometheus_config_dir: "{{ monitoring_base_dir }}/prometheus"
prometheus_data_dir: "{{ monitoring_base_dir }}/prometheus/data"
prometheus_container_name: prometheus
prometheus_docker_image: prom/prometheus:latest

# Grafana configuration
grafana_config_dir: "{{ monitoring_base_dir }}/grafana"
grafana_data_dir: "{{ monitoring_base_dir }}/grafana/data"
grafana_container_name: grafana
grafana_docker_image: grafana/grafana:latest
grafana_admin_user: admin
grafana_admin_password: admin_secure_password

# Alertmanager configuration
alertmanager_config_dir: "{{ monitoring_base_dir }}/alertmanager"
alertmanager_container_name: alertmanager
alertmanager_docker_image: prom/alertmanager:latest
alertmanager_smtp_host: smtp.example.com
alertmanager_smtp_port: 587
alertmanager_smtp_username: alertmanager
alertmanager_smtp_password: your_smtp_password
alertmanager_email_from: alertmanager@yourdomain.com
alertmanager_email_to: admin@yourdomain.com

# Node Exporter configuration
node_exporter_version: 1.3.1
node_exporter_docker_image: prom/node-exporter:v{{ node_exporter_version }}
node_exporter_container_name: node-exporter

# MongoDB configuration
mongodb_config_dir: "{{ monitoring_base_dir }}/mongodb"
mongodb_data_dir: "{{ monitoring_base_dir }}/mongodb/data"
mongodb_docker_image: mongo:latest
mongodb_container_name: mongodb

# InfluxDB configuration
influxdb_config_dir: "{{ monitoring_base_dir }}/influxdb"
influxdb_data_dir: "{{ monitoring_base_dir }}/influxdb/data"
influxdb_docker_image: influxdb:latest
influxdb_container_name: influxdb

# Mosquitto configuration
mosquitto_config_dir: "{{ monitoring_base_dir }}/mosquitto"
mosquitto_data_dir: "{{ monitoring_base_dir }}/mosquitto/data"
mosquitto_docker_image: eclipse-mosquitto:latest
mosquitto_container_name: mosquitto
