---
- name: Validate system requirements
  assert:
    that:
      - ansible_memtotal_mb >= 2048
      - ansible_distribution in ['Ubuntu', 'Debian', 'CentOS', 'RedHat']
    fail_msg: "System does not meet minimum requirements"

- name: Check required ports availability
  wait_for:
    port: "{{ item }}"
    state: stopped
    timeout: 5
  loop:
    - 9090  # Prometheus
    - 9093  # Alertmanager
    - 3000  # Grafana
    - 9100  # Node Exporter
