---
- name: reload grafana
  uri:
    url: http://localhost:3000/api/admin/provisioning/dashboards/reload
    method: POST
    user: "{{ grafana_admin_user }}"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: yes

- name: restart grafana
  docker_container:
    name: grafana
    restart: yes
