---
- name: reload prometheus
  uri:
    url: http://localhost:9090/-/reload
    method: POST
    status_code: 200

- name: restart prometheus
  docker_container:
    name: prometheus
    restart: yes
